name: CodeCov

on:
  push:
    branches:
      - main
      - codecoverage
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest and create code coverage badge
        id: codecov
        run: |
          coverage run -m pytest
          total=`python ./CodeCoverage/code_coverage.py`
          echo "TOTAL=$total" >> $GITHUB_ENV
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 754af2ea2e697f3b71ec00796f5c26b3
          filename: test.json
          label: CodeCov
          message: ${{env.TOTAL}}
          color: green
