name: CodeCov

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest and create code coverage badge
        run: |
          coverage run -m pytest
          total = `python ./CodeCoverage/code_coverage.py`
          if (( $(echo "$total == 84"))); then
            echo "script return correct response"
          fi
          
      # - name: Publish cod cov badge
      #   run: |
      #     set -x
      #     total=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
      #     if (( $(echo "$total <= 50" | bc -l) )) ; then
      #       COLOR=red
      #     elif (( $(echo "$total > 80" | bc -l) )); then
      #       COLOR=green
      #     else
      #       COLOR=orange
      #     fi
      #     curl "https://img.shields.io/badge/coavrege-$total%25-$COLOR" > badge.svg
      #     gsutil  -h "Cache-Control: no-cache" cp badge.svg gs://${SOME_BUCKET}/${PROJECT_NAME}/codcov.svg
      #     gsutil acl ch -u AllUsers:R gs://${SOME_BUCKET}/${PROJECT_NAME}/codcov.svg
