name: CodeCov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest and create code coverage badge
        id: codecov
        run: |
          coverage run -m pytest
          total=`python ./CodeCoverage/code_coverage.py`
          echo "TOTAL=$total" >> $GITHUB_ENV
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.CSC_510_PROJ_3 }}
          gistID: 4974f4b4275b0e2ed9c8776a9c995949
          filename: test.json
          label: CodeCov
          message: ${{env.TOTAL}}
          color: green
