name: CodeCov

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest and create code coverage badge
        run: |
          coverage run -m pytest
          total=`python ./CodeCoverage/code_coverage.py`
          curl "https://img.shields.io/badge/coavrege-$total%25-green" > badge.svg
          gsutil  -h "Cache-Control: no-cache" cp badge.svg gs://adamyen/Simplii/codcov.svg
          gsutil acl ch -u AllUsers:R gs://adamyen/Simplii/codcov.svg
